### ISSUE TITLE
Investigate existing schemas from jsonschemastore.org

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/schemas#10]
There is a set of Ansible schemas that are already published to https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json  and generated using https://github.com/shaded-enmity/ansible-schema-generator which were build by @shaded-enmity

This should be used to track a diff between the two approaches, their outcomes and decide which one should be kept.

**Comment by ssbarnea** [comment]
There is also previous work done at https://github.com/softwarefactory-project/dhall-ansible which should worth investigation.

**Comment by bcoca** [comment]
from a quick check i already found a few flaws with the playbook schema in SchemaStore:

- vars_prompt in play
- vars_files shown only as list of strings can be of list or string, 
- most enums are very incomplete, but just gather_facts subset is glaring enough

**Comment by bcoca** [comment]
There are a few of very hard things for schemas concerning Ansible, a lot of 'irregular' types for fields and variable input accepted.

 I think the worst is 'task action', as it is required, but does not require `action` o  `local_action` keywords, which you can substitute with 'aciton name'. This 'action name' can be an action plugin name or module name.

**Comment by ssbarnea** [comment]
No need to worry about this because we will retire play/tasks schemas as soon we release the new version of vscode extension, the use using the new language server.

On the other hand it may prove useful to keep schemas for other file types, like reqs, meta,...

**Comment by bcoca** [comment]
not a schema, but probably has the data needed to create one https://github.com/ansible/ansible/pull/75446
that + existing module/plugin dump can pave way to make language server be not just version but 'installation' aware

**Comment by ssbarnea** [comment]
Closing as now only our schemas are published on jsonschemas.org, nothing else to investigate.
