### ISSUE TITLE
Add ansible-runtime.json schema for meta/runtime.yml

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/schemas#130]
We need a JSON schema to check validity of `meta/runtime.yml` files.

References:
* https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_structure.html
* https://github.com/ansible-community/ansible-lint/issues/1721

**Comment by ziegenberg** [comment]
I'll try to come with something.

**Comment by ssbarnea** [comment]
@ziegenberg Did you had time to do anything towards this? Asking as I was considering doing it myself today.

**Comment by ziegenberg** [comment]
Go ahead!
