### ISSUE TITLE
Playbook/Tasks 'notify' parameter should accept a string or an array of strings

### ISSUE THREAD

**Issue by kendallgoto** [ansible-community/schemas#184]
In [ansible-tasks.json](f/ansible-tasks.json) and [ansible-playbook.json](f/ansible-playbook.json), the 'notify' parameter is defined with the schema:
```json
"notify": {
          "title": "Notify",
          "type": "string"
        },
```

However, in the latest version of Ansible, this can either be a string or an array of strings, to call multiple handlers.
I believe the correct schema should be:
```json
"notify": {
	"anyOf": [
	{
		"type": "string"
	},
	{
		"items": {
			"type": "string"
		},
		"type": "array"
	}
	],
	"title": "Notify"
},
```

**Comment by Hexta** [comment]
Hey,
I've created a PR #188
