### ISSUE TITLE
Ansible-tasks json-schema tags section

### ISSUE THREAD

**Issue by timurkhisamov** [ansible-community/schemas#69]
According to ansible documentation ansible allows `array` and `integer` types in tags section:
- [link](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#adding-tags-to-individual-tasks)
![image](https://user-images.githubusercontent.com/60743672/120615732-41381b80-c461-11eb-9448-647e27e5d408.png)

Please change on this line
https://github.com/ansible-community/schemas/blob/18d944e69e520bae1bcf9b7bdf6b515f44a43e11/f/ansible-tasks.json#L16225

from: `"type": "array"`
to: `"type": ["array","string"]`

**Comment by ssbarnea** [comment]
Tags can be string or list of strings and few minutes ago I merged a fix.
