### ISSUE TITLE
version property in GalaxyInfoModel expects string but maybe should also allow int

### ISSUE THREAD

**Issue by ziegenberg** [ansible-community/schemas#80]
![Screenshot from 2021-06-10 16-09-32](https://user-images.githubusercontent.com/856916/121548975-be3d3500-ca0d-11eb-8134-ab61d9a617db.png)

`version` property in GalaxyInfoModel expects strings but maybe it should also allow int because the default base structure of a role suggests that int could also be valid for version information: https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/default/role/meta/main.yml.j2

**Comment by ziegenberg** [comment]
@ssbarnea Do you consider this a bug (worth fixing) or should I close my issue?

**Comment by ssbarnea** [comment]
I am not sure yet. The reason I think is better to avoid int and force people to add the quotes is that it may prevent them from wrongly introducing something like `3.10` which will be read as `3.1` to their surprise.

I will ask few others to comment on that.

**Comment by ziegenberg** [comment]
I think your example is a very valid reason to stay with strings. The question is: should this also be changed upstream, so the default template for ansible roles creates strings for version information?
