### ISSUE TITLE
Cannot trigger BeremothTaskModel when using vscode-ansible

### ISSUE THREAD

**Issue by camileck** [ansible-community/schemas#86]
Although schema association is working fine, I cannot trigger autocompletion from BeremothTaskModel definition to get the task-related keywords/module names suggestions. Am I missing anything?

![image](https://user-images.githubusercontent.com/64770136/128500973-e562dc19-a91a-4c49-9803-113c11705e05.png)

**Comment by ssbarnea** [comment]
At this moment tasks and playbook schemas are not used by ansible-language-server.
